<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>MGA_AfterDrive</RootNamespace>
    <AssemblyName>MGA-AfterDrive.Shared</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\app.ico" />
  </ItemGroup>

</Project>
